updated

diff --git a/sourcecode/03_devopspipeline/train-eval-deploy-pipeline.yml b/sourcecode/03_devopspipeline/train-eval-deploy-pipeline.yml
--- a/sourcecode/03_devopspipeline/train-eval-deploy-pipeline.yml
+++ b/sourcecode/03_devopspipeline/train-eval-deploy-pipeline.yml
@@ -18,6 +18,8 @@ trigger:
 variables:
 - template: variable_template.yml
 - group: vgroup-aml-devops-dev
+- name: deploy
+  value: 'no'
 
 
 pool:
@@ -44,12 +46,61 @@ stages:
           # Invoke the Python building and publishing a training pipeline
           python -m 01_DevOpsTrainingPipeline
       displayName: 'Run Azure Machine Learning Pipeline'
-      
-    - task: AzureCLI@1
-      displayName: 'Create directory'
+
+    - task: Bash@3
       inputs:
         azureSubscription: $(ml-ws-connection)
         workingDirectory: $(Build.SourcesDirectory)/sourcecode/03_devopspipeline
+        targetType: 'inline'
+        script: '##vso[task.setvariable variable=deploy]cat ./run_outputs/deploy_details.json  jq | {'deploy'}
+      
+    - task: CopyFiles@2
+      inputs:
+        sourceFolder: '$(Build.SourcesDirectory)/sourcecode/03_devopspipeline'
+        contents: '**/run_outputs/*' 
+        targetFolder: '$(Build.ArtifactStagingDirectory)' 
+        #cleanTargetFolder: false # Optional
+        #overWrite: false # Optional
+        #flattenFolders: false # Optional
+        #preserveTimestamp: false # Optional
+        #retryCount: 0 # Optional
+        #ignoreMakeDirErrors: false # Optional
+
+    - task: PublishBuildArtifacts@1
+      displayName: 'Publish Artifact: drop'
+      inputs:
+        ArtifactName: 'drop'
+        publishLocation: 'Container'
+        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
+        
+    - task: AzureCLI@1
+      inputs:
+        azureSubscription: $(ml-ws-connection)
         scriptLocation: inlineScript
-        scriptType: 'bash'
-        inlineScript: 'mkdir metadata && mkdir models'
+        workingDirectory: $(Build.SourcesDirectory)/sourcecode/03_devopspipeline
+        inlineScript: |
+          set -e # fail on error
+          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
+          # Invoke the Python building and publishing a training pipeline
+          python -m 01_DevOpsTrainingPipeline
+      displayName: 'Run Azure Machine Learning Pipeline'
+      
+  jobs:
+  - job: "Release"
+    condition: ${{ containsValue('deploy', variables['deploy']) }}
+    displayName: "Release"
+    container: mlops
+    timeoutInMinutes: 0
+    steps:
+   
+    - task: AzureCLI@1
+      inputs:
+        azureSubscription: $(ml-ws-connection)
+        scriptLocation: inlineScript
+        workingDirectory: $(Build.SourcesDirectory)/sourcecode/03_devopspipeline
+        inlineScript: |
+          set -e # fail on error
+          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
+          # Invoke the Python building and publishing a training pipeline
+          python -m 02_DeployACI
+      displayName: 'DeployACI'
